services:
  - type: web
    name: sga-pro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PAYTECH_API_KEY
        sync: false
      - key: PAYTECH_API_SECRET
        sync: false
      - key: PAYTECH_ENV
        value: prod
      - key: APP_URL
        sync: false
